version: '3'
services:
  api:
    build: product-service
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'
